server.port: 10000
spring:
  application:
    name: code-executor
  threading:
    virtual:
      enabled: true
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: code-executor
        type: SYNC
        capabilities:
          prompt: false
          completion: false
